# Generated by Django 4.1 on 2022-08-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='content',
            new_name='messages',
        ),
    ]
